name: qdrant
version: '3'
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    hostname: qdrant
    networks:
      - shared_network
    restart: always
    ports:
      - '6333:6333'
    environment:
      QDRANT__TELEMETRY_DISABLED: true
      QDRANT__LOG_LEVEL: WARN
    volumes:
      - ./qdrant_server:/qdrant/storage
networks:
  shared_network:
    name: shared_network
    driver: bridge
