@startuml "Обновление базы знаний"
start
:Запуск скрипта по Cron (ежедн 6:00);
repeat
:Обновление модели эмбеддингов (all-MiniLM-L6-v2) ;
:Чтение документов (каталог import_docs);
:Разбивка документов на чанки (1000 токенов/чанк);
:Загрузка чанков с эмбеддингами в Qdrant (http://localhost:6333);
repeat while (Ошибка и кол-во попыток <=3)
stop
@enduml


